sudo: required
services:
  - docker
  - postgresql
language: go
go:
  - 1.6
env:
  - GO15VENDOREXPERIMENT=1
before_install:
  - env | grep -i travis
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/Masterminds/glide
install:
  - bash build_assets.bash production
  - glide install
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - go test -race -v `go list ./... | grep -v /vendor/`
after_success:
  - bash build.bash production
  - [[ $TRAVIS_PULL_REQUEST -eq "false" ]] && case $TRAVIS_BRANCH in master) docker build -t tf2stadium/helen:latest . ;; dev) docker build -t tf2stadium/helen:dev . ;; esac
  - [[ $TRAVIS_PULL_REQUEST -eq "false" ]] && case $TRAVIS_BRANCH in master) docker push tf2stadium/helen:latest ;; dev) docker push tf2stadium/helen:dev ;; esac
