language: go
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database tf2stadium;' -U postgres
script:
- go test ./...
env:
  global:
    secure: YF5jtGKaQneR5JxF+Wlf7zwPRISpIX1Wv/WGiGLJ0/DEzl2dt5StXd1Db8xhpXfOYKWYI0KYQpbzgz2JpQn6SbOnemvTQ191tBSgh39a0D39/t5FWdouf+LzVW04NmRLpeb3A/kmbNFi89xiCCwXNTxnm1crnQZtnrf/WdLNdiM6+wtfzI3z58bFvDHWUWBku2spQDJniAusolP8etMl23srzKZ4EmrSzmKH+Fhg8GHifA2jXrG9x1tyzUH6tHTGNZKc/9jb7VeOu6/GXVc289bkr7CiHrPtErr8IhONDYfZpgaw/5hvCY47/UYDIDe00yFK3y9j4hM6pzbzkXPec9eRRZkL6sD62ieKnJ36BHsQjRoT9mI8U8vBJuLhr93o06suJFxr6mKlzLhNK8+/47wOv/DNVCWa2Xf15Mrcy8SdNXfotxaM6bOgtyP/3oHmSqUPbk6MipWNAZyFyI8/QvHQAGlGozOEBvxhpqFMOmyNk8s9vqJpmduV0Urj+nqEPowdsYMPS0nVYM7/l44CokrSYqvW5w2gTfgtRpPY6C/T3PtFL/SyOx6Anfj4FJVINwn7V/Hj7gbd4pz4nB5FMbo4HpABwfUgs9QnWqIKz8K//pEUp4EaDT0jRiWeyfQagLsYukelupN1tFYFtpHFclmf4Tv8ZwT7XqJcJuT/JjY=
