sudo: required
services:
  - docker
language: go
go:
  - 1.6
env:
  - GO15VENDOREXPERIMENT=1
before_install:
  - go get github.com/Masterminds/glide
install:
  - make assets -B
  - glide install
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - make static -B
  - case $TRAVIS_BRANCH in master) docker build -t tf2stadium/helen:latest . ;; dev) docker build -t tf2stadium/helen:dev . ;; esac 
after_success:
  - case $TRAVIS_BRANCH in master) docker push tf2stadium/helen:latest ;; dev) docker push tf2stadium/helen ;; esac
